#!/usr/bin/env bash
set -euo pipefail

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# Teardown — undo what `make init` configured
#
# Cleans up resources both inside and outside the repo:
#   - Self-hosted runner (unregister + remove from disk)
#   - GitHub repository (optional — asks for confirmation)
#   - Local config (.env, .github/, generated scripts)
#   - Git state (reset to pre-init or remove origin)
#
# Usage: make teardown
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

# ── Colors ────────────────────────────────────────────
BOLD='\033[1m'
DIM='\033[2m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RED='\033[0;31m'
RESET='\033[0m'

ok()     { echo -e "${GREEN}✓${RESET} $1"; }
warn()   { echo -e "${YELLOW}!${RESET} $1"; }
fail()   { echo -e "${RED}✗${RESET} $1"; }
info()   { echo -e "${DIM}$1${RESET}"; }

confirm() {
  local prompt="$1" default="${2:-n}"
  if [ "$default" = "y" ]; then
    echo -en "${BOLD}$prompt${RESET} ${DIM}[Y/n]${RESET}: " >&2
  else
    echo -en "${BOLD}$prompt${RESET} ${DIM}[y/N]${RESET}: " >&2
  fi
  read -r answer
  answer="${answer:-$default}"
  [[ "$answer" =~ ^[Yy] ]]
}

echo -e "${BOLD}"
echo "  ┌─────────────────────────────────────┐"
echo "  │  Project Teardown                   │"
echo "  │  Undo init and clean up resources   │"
echo "  └─────────────────────────────────────┘"
echo -e "${RESET}"

# ── Detect what was configured ────────────────────────
GITHUB_REPO=""
if [ -f "$ROOT_DIR/.env" ]; then
  GITHUB_REPO=$(grep -E '^GITHUB_REPO=' "$ROOT_DIR/.env" 2>/dev/null | cut -d'=' -f2- | tr -d '[:space:]' || true)
fi

REPO_SLUG=""
if [ -n "$GITHUB_REPO" ]; then
  REPO_SLUG="$(echo "$GITHUB_REPO" | tr '/' '-')"
fi

# ── 1. Remove self-hosted runner ──────────────────────
echo ""
RUNNER_DIR="$HOME/.github-runner/${REPO_SLUG}"

if [ -n "$REPO_SLUG" ] && [ -d "$RUNNER_DIR" ]; then
  info "Self-hosted runner found at: $RUNNER_DIR"
  if confirm "Remove self-hosted runner?"; then
    if [ -f "$RUNNER_DIR/svc.sh" ]; then
      (cd "$RUNNER_DIR" && ./svc.sh stop 2>/dev/null || true)
      (cd "$RUNNER_DIR" && ./svc.sh uninstall 2>/dev/null || true)
    fi

    # Unregister from GitHub
    if [ -n "$GITHUB_REPO" ] && command -v gh &>/dev/null; then
      REG_TOKEN=""
      REG_TOKEN=$(gh api "repos/${GITHUB_REPO}/actions/runners/registration-token" --method POST --jq '.token' 2>/dev/null || true)
      if [ -n "$REG_TOKEN" ] && [ -f "$RUNNER_DIR/config.sh" ]; then
        (cd "$RUNNER_DIR" && ./config.sh remove --token "$REG_TOKEN" 2>/dev/null || true)
      fi
    fi

    rm -rf "$RUNNER_DIR"
    ok "Runner removed from $RUNNER_DIR"

    # Clean up parent if empty
    RUNNER_PARENT="$HOME/.github-runner"
    if [ -d "$RUNNER_PARENT" ] && [ -z "$(ls -A "$RUNNER_PARENT" 2>/dev/null)" ]; then
      rmdir "$RUNNER_PARENT" 2>/dev/null || true
      ok "Removed empty $RUNNER_PARENT"
    fi
  else
    info "Skipped runner removal"
  fi
else
  info "No self-hosted runner found"
fi

# ── 2. Delete GitHub repository ───────────────────────
echo ""
if [ -n "$GITHUB_REPO" ] && command -v gh &>/dev/null; then
  REPO_EXISTS=false
  gh repo view "$GITHUB_REPO" &>/dev/null && REPO_EXISTS=true

  if [ "$REPO_EXISTS" = true ]; then
    warn "GitHub repository: $GITHUB_REPO"
    if confirm "Delete the GitHub repository? (THIS CANNOT BE UNDONE)"; then
      if confirm "Type 'yes' to confirm deletion of $GITHUB_REPO" "n"; then
        DELETE_EXIT=0
        DELETE_OUTPUT=$(gh repo delete "$GITHUB_REPO" --yes 2>&1) || DELETE_EXIT=$?
        if [ $DELETE_EXIT -eq 0 ]; then
          ok "Deleted repository: $GITHUB_REPO"
        else
          fail "Failed to delete repository: $DELETE_OUTPUT"
          info "Delete manually: gh repo delete $GITHUB_REPO --yes"
        fi
      else
        info "Skipped repository deletion"
      fi
    else
      info "Keeping repository: $GITHUB_REPO"
    fi
  else
    info "Repository $GITHUB_REPO does not exist on GitHub"
  fi
else
  info "No GitHub repository to clean up"
fi

# ── 3. Clean local files generated by init ────────────
echo ""
if confirm "Remove local init artifacts (.env, generated scripts, .github/)?"; then
  # Remove generated files
  if [ -f "$ROOT_DIR/.env" ]; then
    rm "$ROOT_DIR/.env"
    ok "Removed .env"
  fi

  # Remove .github/ (was moved from _github/ during init)
  if [ -d "$ROOT_DIR/.github" ] && [ ! -d "$ROOT_DIR/_github" ]; then
    rm -rf "$ROOT_DIR/.github"
    ok "Removed .github/"
    info "Re-run 'make init' to restore workflows from _github/"
  fi

  # Remove generated scripts
  for f in scripts/checks/lint.sh scripts/checks/test.sh scripts/setup.sh; do
    if [ -f "$ROOT_DIR/$f" ]; then
      rm "$ROOT_DIR/$f"
      ok "Removed $f"
    fi
  done

  # Remove generated directories
  for d in .worktrees .deploy-artifacts; do
    if [ -d "${ROOT_DIR:?}/$d" ]; then
      rm -rf "${ROOT_DIR:?}/$d"
      ok "Removed $d/"
    fi
  done

  ok "Local artifacts cleaned"
else
  info "Keeping local files"
fi

# ── 4. Reset git state ───────────────────────────────
echo ""
if confirm "Reset git to pre-init state? (discards uncommitted changes)"; then
  cd "$ROOT_DIR"

  # Remove the init commit if it's the latest
  LAST_MSG=$(git log -1 --format="%s" 2>/dev/null || true)
  if [[ "$LAST_MSG" == Initialize\ project:* ]]; then
    git reset --soft HEAD~1
    git reset HEAD .
    ok "Undid init commit (changes are unstaged)"
  fi

  # Remove origin if it points to a deleted repo
  if [ -n "$GITHUB_REPO" ]; then
    CURRENT_ORIGIN=$(git remote get-url origin 2>/dev/null || true)
    if [[ "$CURRENT_ORIGIN" == *"$GITHUB_REPO"* ]]; then
      if confirm "Remove origin remote ($CURRENT_ORIGIN)?"; then
        git remote remove origin
        ok "Removed origin remote"
      fi
    fi
  fi
else
  info "Git state unchanged"
fi

# ── Done ──────────────────────────────────────────────
echo ""
echo -e "${BOLD}Teardown complete.${RESET}"
echo ""
info "To start fresh, run: make init"
info "To delete this directory entirely: cd .. && rm -rf '$(basename "$ROOT_DIR")'"
